version: '2'

services:
  db:
    container_name: db-box
    image: postgres:9.4
    volumes:
      - ./db_box/scripts:/docker-entrypoint-initdb.d
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - backend

  app:
    container_name: app-box    
    build: app_box/
    networks:
      - backend
    depends_on:
      - db
    ports:
      - '80:80'

networks:
  backend:
