#
# Dockerfile on ubuntu for app
# nginx - uwsgi - app(django)
#

FROM ubuntu:16.04

RUN mkdir /data
WORKDIR /data

RUN apt-get update -y && apt-get -y upgrade -y \
    && apt-get install -y nginx python3 python3-pip

COPY requirements.txt /data
RUN pip3 install --no-cache-dir -r requirements.txt

COPY . /data

RUN ln -s /data/conf/nginx.conf /etc/nginx/sites-enabled/
RUN echo 'daemon off;' >> /etc/nginx/nginx.conf
RUN nginx -t


EXPOSE 80

# CMD ['uwsgi', '--ini', 'conf/uwsgi.ini']
# CMD service nginx start
CMD ./start.sh
