#
# Dockerfile for db
# postgres
#

FROM postgres:9.4
COPY *.sql /docker-entrypoint-initdb.d/

USER postgres

RUN    /etc/init.d/postgresql start &&\
    psql --command "CREATE USER elect WITH SUPERUSER PASSWORD 'electword';" &&\
    createdb -O dbelectrobit elect

# RUN echo "host all  all    0.0.0.0/0  md5" >> /etc/postgresql/9.3/main/pg_hba.conf

# RUN echo "listen_addresses='*'" >> /etc/postgresql/9.3/main/postgresql.conf

EXPOSE 54001

VOLUME  ["/etc/postgresql", "/var/log/postgresql", "/var/lib/postgresql"]

CMD ["/usr/lib/postgresql/9.3/bin/postgres", "-D", "/var/lib/postgresql/9.3/main", "-c", "config_file=/etc/postgresql/9.3/main/postgresql.conf"]